### ISSUE TITLE
Elixir 1.6 support

### ISSUE THREAD

**Issue by vjousse** [wende/elchemy#261] opened 2018-01-26 22:21 UTC
I am trying `elchemy` for the first time ( following https://hackernoon.com/elmchemy-write-type-safe-elixir-code-with-elms-syntax-part-1-introduction-8968b76d721d ), and I get a compilation error when doing `mix text` after having created a new project from scratch. Full log at the bottom of the issue.

I'm using `archlinux`. Here are some version numbers:
```
$ elixir -v
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0 (compiled with OTP 20)
```
```
$ elm-github-install -v
elm-install 1.6.1
```
```
$ npm -g list elchemy
/home/vjousse/.npm-global/lib
└── elchemy@0.5.5
```
```
$ mix -v
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.6.0 (compiled with OTP 20)
```

Full steps to reproduce the issue on my computer:
```
$ mix new article_example_elchemy
$ cd article_example_elchemy
$ elchemy init
```

Change the generated `mix.exs` to:
```elixir
defmodule ArticleExampleElchemy.MixProject do
  use Mix.Project

  def project do
    [
      app: :article_example_elchemy,
      version: "0.1.0",
      elixir: "~> 1.6",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
    |> Code.eval_file("elchemy.exs").init
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"},
    ]
  end
end

```
```
$ mix test
```
Then I got this error:
```
== Compilation error in file lib/Elchemy/XDebug.elchemy.ex ==
** (MatchError) no match of right hand side value: {:spec, {:puts_, 2}, 36, {:type, 34, :fun, [{:type, 34, :product, [{:user_type, 34, :device, []}, {:type, 34, :any, []}]}, {:type, 34, :any, []}]}}
    lib/Elchemy/XDebug.elchemy.ex:36: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
could not compile dependency :elchemy, "mix compile" failed. You can recompile this dependency with "mix deps.compile elchemy", update it with "mix deps.update elchemy" or clean it with "mix deps.clean elchemy"
```
You can get the full log of the commands here: [fulllog.txt](https://github.com/wende/elchemy/files/1669354/fulllog.txt)

**Comment by wende** [comment] 2018-01-27 04:31
Yup. Been able to reproduce the same result using Elixir 1.6
Adjusting the title of the issue

**Comment by wende** [comment] 2018-01-27 16:19
@vjousse 
Just solved that in PR #262. 
Will merge and release it with next patch version later this weekend

**Comment by wende** [comment] 2018-01-28 01:12
Released in version 0.5.6
https://github.com/wende/elchemy/releases

**Closed by wende** 2018-01-28 01:12 UTC

**Comment by vjousse** [comment] 2018-01-29 15:15
I still have errors when running `mix test`, is it expected?
![mix_test](https://user-images.githubusercontent.com/154904/35517735-a0df2c8c-050f-11e8-9083-ab30b5df97c5.png)

**Comment by wende** [comment] 2018-01-29 15:24
@vjousse  Looks like you removed the `hello` function from the example module that gets created when running `elchemy init`

If show me the output of `tree -L 2` and `cat lib/elchemy_test.ex` in your root project folder I should be able to tell exactly what's the issue.

(BTW giving a name to a project with `_test` at the end might be causing some problems with elixir, `elchemy_test_test.exs` seems like it might become problematic quite quickly)

**Comment by vjousse** [comment] 2018-01-29 15:38
I have a first error when running `mix test`.

```
== Compilation error in file elm/Elchemy/Native/NativeDict.ex ==
** (CompileError) elm/Elchemy/Native/NativeDict.ex:2: module Elchemy.XBasics is not loaded and could not be found
    expanding macro: Elchemy.import_std/0
    elm/Elchemy/Native/NativeDict.ex:2: Native.Dict (module)
    expanding macro: Elchemy.__using__/1
    elm/Elchemy/Native/NativeDict.ex:2: Native.Dict (module)
could not compile dependency :elchemy, "mix compile" failed. You can recompile this dependency with "mix deps.compile elchemy", update it with "mix deps.update elchemy" or clean it with "mix deps.clean elchemy"
```
The I had to rerun `mix test` and now it's ok. That's very strange, errors seems non deterministic.

**Comment by wende** [comment] 2018-01-29 15:42
@vjousse 
Usually when this happens it means that either Elchemy wasn't initialized properly or there was some artifacts left.
Whenever in doubt `elchemy clean && mix compile` solves most of the issues. It cleans all the caches, artifacts, compiled files, deps and so on.
