### ISSUE TITLE
mix test errors out, then hangs, then errors out again

### ISSUE THREAD

**Issue by omnibs** [wende/elchemy#168] opened 2017-08-20 05:42 UTC
I tried following [the introductory blogpost](https://hackernoon.com/elmchemy-write-type-safe-elixir-code-with-elms-syntax-part-1-introduction-8968b76d721d) and it didn't work.

When I run "mix test" I get some errors. If I run it again it starts compiling but hangs. I noticed some `yes n` processes running and decided to kill them. This unfroze compilation, but it still finishes with errors.

Here's a video of what happens:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/ygirqhXlygw/0.jpg)](https://www.youtube.com/watch?v=ygirqhXlygw)

<details><summary>* Expand here for the full log from the video</summary>

```
➜  elchemytest mix test
Resolving packages...
  ▶ Getting updates for: elm-lang/core
error: git '--git-dir=/Users/juliano/.elm-install/github.com/elm-lang/core/.git' '--work-tree=/Users/juliano/.elm-install/github.com/elm-lang/core' reset '--hard'  2>&1:fatal: Unable to create '/Users/juliano/.elm-install/github.com/elm-lang/core/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.. Use --trace to view backtrace
find: elm/../elm-stuff/packages: No such file or directory
find: elm/../elm-stuff/packages: No such file or directory
----------
Compiling elm/Hello.elm
Error: Your .elm/packages/ directory may be corrupted. I was led to believe that
wende/elchemy-core existed, but I could not find anything when I went to look up
the published versions of this package.


^C
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C%                                                                                                                                    ➜  elchemytest mix test
Resolving packages...
  ▶ Getting updates for: elm-lang/core
  ▶ Getting updates for: wende/elchemy-core
Solving dependencies...
  ● elm-lang/core - https://github.com/elm-lang/core (5.1.1)
  ● wende/elchemy-core - https://github.com/wende/elchemy-core (0.4.14)
Packages configured successfully!
FOUND elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/Native/NativeDict.ex
TO elm/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/Native/NativeDict.ex
FOUND elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/lib/glue.ex
TO elm/../elm-deps/wende/elchemy-core/0.4.14/lib/glue.ex
FOUND elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/lib/spec.ex
TO elm/../elm-deps/wende/elchemy-core/0.4.14/lib/spec.ex
FOUND elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/lib/test.ex
TO elm/../elm-deps/wende/elchemy-core/0.4.14/lib/test.ex
----------
Compiling elm/Hello.elm
Success! Compiled 34 modules.
Successfully generated .elchemy_output_tmp.js
#1
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XBasics.elm
#2
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XChar.elm
#3
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XDebug.elm
#4
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XDict.elm
#5
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XList.elm
#6
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XMaybe.elm
#7
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XResult.elm
#8
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XSet.elm
#9
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XString.elm
#10
----------
Compiling elm/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XTuple.elm
#11
-- Linking files --
Linking: lib/Hello.elm
To: lib/Hello.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XBasics.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XBasics.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XChar.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XChar.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XDebug.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XDebug.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XDict.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XDict.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XList.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XList.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XMaybe.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XMaybe.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XResult.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XResult.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XSet.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XSet.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XString.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XString.elchemy.ex
Linking: lib/../elm-stuff/packages/wende/elchemy-core/0.4.14/elm/Elchemy/XTuple.elm
To: lib/../elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XTuple.elchemy.ex
Compiling 16 files (.ex)
warning: redefining module Elchemy.XResult (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XResult.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XResult.elchemy.ex:3

warning: redefining module Elchemy.XBasics (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XBasics.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XBasics.elchemy.ex:3

warning: redefining module Elchemy.XChar (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XChar.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XChar.elchemy.ex:3

warning: redefining module Elchemy.XDict (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XDict.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XDict.elchemy.ex:3

warning: redefining module Elchemy.XDebug (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XDebug.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XDebug.elchemy.ex:3

warning: redefining module NativeDict (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.NativeDict.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/Native/NativeDict.ex:1

warning: redefining module Elchemy.XMaybe (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XMaybe.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XMaybe.elchemy.ex:3

warning: redefining module Elchemy.XList (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XList.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XList.elchemy.ex:3

warning: redefining module Elchemy.XSet (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XSet.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XSet.elchemy.ex:3

warning: redefining module Elchemy.XTuple (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XTuple.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XTuple.elchemy.ex:3

warning: redefining module Elchemy.Glue (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.Glue.beam)
  elm-deps/wende/elchemy-core/0.4.14/lib/glue.ex:1

warning: redefining module Elchemy.XString (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.XString.beam)
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XString.elchemy.ex:3

warning: defp take_arguments/1 is private, @doc's are always discarded for private functions/macros/types
  elm-deps/wende/elchemy-core/0.4.14/lib/glue.ex:72

warning: redefining module Elchemy.Spec (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.Spec.beam)
  elm-deps/wende/elchemy-core/0.4.14/lib/spec.ex:1

warning: function extract_path/1 is unused
  elm-deps/wende/elchemy-core/0.4.14/lib/spec.ex:245

warning: variable "r" is unused
  elm-deps/wende/elchemy-core/0.4.14/lib/spec.ex:47

warning: variable "other" is unused
  elm-deps/wende/elchemy-core/0.4.14/lib/spec.ex:370

warning: redefining module Elchemy.SpecError (current version loaded from /Users/juliano/.mix/archives/elchemy-0.4.14/elchemy-0.4.14/ebin/Elixir.Elchemy.SpecError.beam)
  elm-deps/wende/elchemy-core/0.4.14/lib/spec.ex:383

warning: function map_/2 is unused
  elm-deps/wende/elchemy-core/0.4.14/elm/Elchemy/XString.elchemy.ex:937

Generated elchemytest app

20:20:40.825 [error] Loading of /Users/juliano/git/test/elchemytest/_build/test/lib/elchemytest/ebin/Elixir.ElchemyTest.beam failed: :badfile


20:20:40.825 [error] beam/beam_load.c(1412): Error loading module 'Elixir.ElchemyTest':
  module name in object code is Elixir.Elchemytest


....

Finished in 0.03 seconds
4 tests, 0 failures

Randomized with seed 809361
```
</details>

My setup:

* macos 10.12.6
* Elixir 1.5.0
* Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

**Comment by wende** [comment] 2017-08-20 08:55
A recent change introduced yes because we're using 
https://github.com/gdotdesign/elm-github-install
To install packages and sometimes `elm-make` has newer packages and it wants to install them.

I will have to track down what's hanging. 
Good call though

**Comment by wende** [comment] 2017-08-20 10:05
Ok. I changed the release pipeline a little to avoid problems like that. Can you try version 4.30 with:

```
cd your_project
npm install -g elchemy
elchemy clean
elchemy init
mix test
```

Apart from 4 warnings it should be working fine now

**Comment by omnibs** [comment] 2017-08-20 19:32
Thanks for the swift reply! Wow!

I followed the steps, it didn't hang anymore but `mix test` still errors out:

```
Compiling 17 files (.ex)
Generated elchemytest app

16:25:45.962 [error] Loading of /Users/juliano/git/test/elchemytest/_build/test/lib/elchemytest/ebin/Elixir.ElchemyTest.beam failed: :badfile


16:25:45.962 [error] beam/beam_load.c(1412): Error loading module 'Elixir.ElchemyTest':
  module name in object code is Elixir.Elchemytest


....

Finished in 0.03 seconds
4 tests, 0 failures
```

This doesn't seem to be preventing me from trying out basic functionality in Elchemy. Tests pass, I can also successfully make them fail. Not sure what implications failing to load this stuff might have.

**Comment by wende** [comment] 2017-08-20 19:51
@omnibs 
This output seems to be a surprise for me. I can't reproduce it and don't really know what might be the cause
Hit me up if it turns out it makes something impossible to use.
Closing for now

**Closed by wende** 2017-08-20 19:51 UTC
